name: CI - Deploy Ichigo Image to DockerHub
on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Get tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        id: tag
        uses: dawidd6/action-get-tag@v1
  build-docker-x64:
    needs: get-tag
    uses: ./.github/workflows/template-docker.yaml
    secrets: inherit
    with:
      runs-on: ubuntu-latest
      docker-file: api/Dockerfile
      context: api
      readme-file: ./README.md
      docker-repo-name: menloltd/ichigo
      tags: menloltd/ichigo:{{ needs.get-tag.outputs.new_version }}